#!/bin/bash

###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

# Building everything up
echo "Building everything up (jupyter lab build)"
jupyter lab build 

###############################################################
#             moving to a local installation folder           #
###############################################################

mkdir ~/resources/local
cd    ~/resources/local

###############################################################
#             cassandra installation commands                   #
###############################################################

export CASSANDRA_VERSION=4.0
echo "export CASSANDRA_VERSION=${CASSANDRA_VERSION}" >> ~/.bashrc
echo "export CASSANDRA_VERSION=${CASSANDRA_VERSION}" >> ~/.profile

export CASSANDRA_HOME=$(pwd)/apache-cassandra-${CASSANDRA_VERSION}
echo "export CASSANDRA_HOME=${CASSANDRA_HOME}"       >> ~/.bashrc
echo "export CASSANDRA_HOME=${CASSANDRA_HOME}"       >> ~/.profile

  
wget -q https://dlcdn.apache.org/cassandra/${CASSANDRA_VERSION}/apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz
# wget -q https://archive.apache.org/dist/cassandra/${CASSANDRA_VERSION}/apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz

tar xzf apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz
rm      apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz

# adding bin and sbin to $path
echo "export PATH=\$PATH:\$CASSANDRA_HOME/bin"  >> ~/.bashrc
echo "export PATH=\$PATH:\$CASSANDRA_HOME/bin"  >> ~/.profile

